apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: will42-ingress
  namespace: dev
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: traefik
  rules:
  - http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: will42
            port:
              number: 8888