apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: will42
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Gpatrix/42.lchauvet.Inception-of-Things.manifests
    targetRevision: HEAD
    path: main
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      enabled: true
      prune: true
      selfHeal: true