# app-three.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-three
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app-three
  template:
    metadata:
      labels:
        app: app-three
    spec:
      containers:
      - name: app-three
        image: paulbouwer/hello-kubernetes:1.8
        ports:
        - containerPort: 8080
        env:
          - name: MESSAGE
            value: "Hello from app3."
---
apiVersion: v1
kind: Service
metadata:
  name: app-three
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: app-three