# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/debian12"
  config.vm.box_version = "4.3.12"
end

#   config.vm.define "mduvey" do |mduveyS|
#     config.vm.hostname = "mduveyS"
#     config.vm.network "public_network", ip: "192.168.56.110", bridge: "enp0s3"
#     config.vm.provider "virtualbox" do |vb|
#       vb.gui = false
#       vb.name = "mduveyS VirtualBox"
#       vb.memory = "1024"
#       vb.cpus = 2
#     end
#   end