# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "hashicorp-education/ubuntu-24-04"
  config.vm.box_version = "0.1.0"

  config.vm.network "forwarded_port", guest: 80, host: 8080

  # TODO install k3s ob both machines
  # TODO launch k3s on first in Server
  # TODO launch k3s on second in ServerWorker

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  config.vm.define "mduvey" do |mduveyS|
    config.vm.hostname = "mduveyS"
    config.vm.network "public_network", ip: "192.168.56.110", bridge: "enp0s3"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "mduveyS VirtualBox"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  config.vm.define "lchauvet" do |mduveyS|
    config.vm.hostname = "mduveySW"
    config.vm.network "public_network", ip: "192.168.56.120", bridge: "enp0s3"
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "mduveySW VirtualBox"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
end
