# # -*- mode: ruby -*-
# # vi: set ft=ruby :

SERVICES = {
  'mduveyS' => {
    ip: '192.168.56.10'
  },
  'mduveySW' => {
    ip: '192.168.56.11'
  }
}

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  # Every Vagrant development environment requires a box. You can search for
  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "ubuntu/bionic64"
  # config.vm.box_version = "3.21.2-r0"

  config.vm.network "forwarded_port", guest: 80, host: 4269

  # TODO install k3s ob both machines
  # TODO launch k3s on first in Server
  # TODO launch k3s on second in ServerWorker

  # config.vm.provision "shell", inline: <<-SHELL
  #   apt-get update
  #   apt-get install -y apache2
  # SHELL

  config.vm.define "mduveyS" do |mduveyS|
    mduveyS.vm.hostname = "mduveyS"
    mduveyS.vm.network "public_network", ip: SERVICES['mduveyS'][:ip], bridge: "enp0s3"
    mduveyS.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "mduveyS"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  config.vm.define "mduveySW" do |mduveySW|
    mduveySW.vm.hostname = "mduveySW"
    mduveySW.vm.network "public_network", ip: SERVICES['mduveySW'][:ip], bridge: "enp0s3"
    mduveySW.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "mduveySW"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
end
