# # -*- mode: ruby -*-
# # vi: set ft=ruby :

SERVICES = {
  'mduveyS' => {
    ip: '192.168.56.110'
  },
  'mduveySW' => {
    ip: '192.168.56.111'
  }
}

Vagrant.configure("2") do |config|

  # boxes at https://vagrantcloud.com/search.
  config.vm.box = "onlyoffice/base-debian13"
  config.vm.box_version = "1.0.0"
  config.vm.provision "file", source: ".env", destination: "/home/vagrant/.env"

  config.vm.define "mduveyS" do |mduveyS|
    mduveyS.vm.hostname = "mduveyS"
    mduveyS.vm.network "public_network", ip: SERVICES['mduveyS'][:ip], bridge: "enp0s3"
    mduveyS.vm.network "private_network", ip: SERVICES['mduveyS'][:ip]
    mduveyS.vm.network "forwarded_port", guest: 80, host: 4270
    mduveyS.vm.provision "shell", path: "./scripts/install_server.sh"
    mduveyS.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "mduveyS"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end

  config.vm.define "mduveySW" do |mduveySW|
    mduveySW.vm.hostname = "mduveySW"
    mduveySW.vm.network "public_network", ip: SERVICES['mduveySW'][:ip], bridge: "enp0s3"
    mduveySW.vm.network "private_network", ip: SERVICES['mduveySW'][:ip]
    mduveySW.vm.network "forwarded_port", guest: 80, host: 4269
    mduveySW.vm.provision "shell", path: "./scripts/install_client.sh"
    mduveySW.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.name = "mduveySW"
      vb.memory = "1024"
      vb.cpus = 2
    end
  end
end
