apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: mycluster
servers: 1
agents: 2
kubeAPI:
  host: "localhost"
  hostIP: "127.0.0.1"
  hostPort: "6445"
image: rancher/k3s:v1.20.4-k3s1
token: superSecretToken # TODO Change this token to a non hardcoded value
volumes:
  - volume: /my/host/path:/path/in/node
    nodeFilters:
      - server:0
      - agent:*
ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer


